#!/bin/bash

timedatectl set-ntp true
mkfs.fat -F32 /dev/sda1
mkfs.ext4 /dev/sda2
mount /dev/sda2 /mnt
pacstrap /mnt base linux linux-lts linux-zen linux-firmware 
genfstab -U /mnt >> /mnt/etc/fstab
arch-chroot /mnt

