#!/bin/bash
echo "This script installs for btrfs"
ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
hwclock --systohc
sed -i '160s/.//' /etc/locale.gen
locale-gen
read -sp "Input hostname" hostname
echo "LANG=en_GB.UTF-8" >> /etc/locale.conf
echo $hostname >> /etc/hostname
echo "127.0.0.1 localhost" >> /etc/hosts
echo "::1       localhost" >> /etc/hosts
echo "127.0.1.1 $hostname.localdomain $hostname" >> /etc/hosts
echo root:password | chpasswd

# tlp if on laptop
#pacman -S tlp
#systemctl enable tlp

pacman -S grub grub-btrfs efibootmgr networkmanager network-manager-applet dialog mtools dosfstools reflector base-devel linux-zen-headers avahi xdg-user-dirs xdg-utils gvfs gvfs-smb nfs-utils inetutils dnsutils alsa-utils pipewire pipewire-alsa pipewire-pulse pipewire-jack bash-completion openssh rsync reflector acpi acpi_call virt-manager qemu qemu-arch-extra edk2-ovmf bridge-utils dnsmasq vde2 openbsd-netcat iptables-nft ipset firewalld sof-firmware nss-mdns acpid os-prober

# cockpit for remote vm management
pacman -S cockpit udisks2
systemctl enable --now cockpit.socket

# bluetooth
#pacman -S bluez bluez-utils 
#systemctl enable bluetooth

#printer services
pacman -S cups hplip
systemctl enable cups.service

# pacman -S --noconfirm xf86-video-amdgpu
pacman -S --noconfirm nvidia nvidia-utils nvidia-settings
# pacman -S --noconfirm xf86-video-qxl

grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
grub-mkconfig -o /boot/grub/grub.cfg

systemctl enable NetworkManager
systemctl enable avahi-daemon
systemctl enable reflector.timer
systemctl enable fstrim.timer
systemctl enable libvirtd
systemctl enable firewalld
systemctl enable acpid
# systemctl enable sshd

read -sp "Input username" username
useradd -m $username
echo $username:password | chpasswd
usermod -aG libvirt $username

echo "$username ALL=(ALL) ALL" >> /etc/sudoers.d/$username


printf "\e[1;32mDone! Change mkinitcpio for btrfs, then type exit, umount -a and reboot.\e[0m"